import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import { Header } from "@/components/organism/header";
import { ScrollProvider } from "@/provider/ScrollProvider";
import { Footer } from "@/components/organism/footer";
import { SocialSidebar } from "@/components/molecules/social-sidebar";
import { getActiveSocialLinks } from "@/sanity/lib/client";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Asif ",
  description: "Generated by create next app",
};

export const revalidate = 30;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const socialData = await getActiveSocialLinks();
  
  return (
    <html lang="en" className="">
      <ScrollProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col bg-background `}
        >
          <Header />
          <SocialSidebar socialLinks={socialData?.socialLinks} />
          <main className="flex-1">{children}</main>
          <Footer />
        </body>
      </ScrollProvider>
    </html>
  );
}
